// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OperationNexus.Api.Data;
using Pgvector;

#nullable disable

namespace OperationNexus.Api.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260320224457_AddResumeSessionEmbeddingLink")]
    partial class AddResumeSessionEmbeddingLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.MatchSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ConstraintsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JdSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchFlowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PipelineStagesJson")
                        .HasColumnType("text");

                    b.Property<string>("PipelineStatsJson")
                        .HasColumnType("text");

                    b.Property<string>("ResultsJson")
                        .HasColumnType("text");

                    b.Property<string>("SearchMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopN")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.ToTable("MatchSessions");
                });

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.OpenPositionCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CandidateRequisitionId")
                        .HasColumnType("integer");

                    b.Property<string>("CandidateStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("boolean");

                    b.Property<string>("MainSkill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OpenPositionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<string>("StartDate")
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OpenPositionId", "CandidateRequisitionId")
                        .IsUnique();

                    b.ToTable("OpenPositionCandidates");
                });

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.ResumeEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)");

                    b.Property<bool>("IsBench")
                        .HasColumnType("boolean");

                    b.Property<string>("ResumeText")
                        .HasColumnType("text");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UpstreamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("ResumeEmbeddings");
                });

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.ResumeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateUpstreamId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CompletedStepsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CurrentStepKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeUpstreamId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileType")
                        .HasColumnType("text");

                    b.Property<string>("OriginalResumeText")
                        .HasColumnType("text");

                    b.Property<string>("ProcessingMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefinementMode")
                        .HasColumnType("text");

                    b.Property<string>("ResumeContentJson")
                        .HasColumnType("text");

                    b.Property<int?>("ResumeEmbeddingId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StepperContextJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UploadStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VectorizationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateUpstreamId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("EmployeeUpstreamId");

                    b.HasIndex("ResumeEmbeddingId");

                    b.ToTable("ResumeSessions");
                });

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.SyncedCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateStatus")
                        .HasColumnType("text");

                    b.Property<bool>("CoeCertified")
                        .HasColumnType("boolean");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<decimal?>("CurrentSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasResume")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastStatusUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MainSkill")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResumeDateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResumeFilename")
                        .HasColumnType("text");

                    b.Property<int?>("ResumeNoteId")
                        .HasColumnType("integer");

                    b.Property<string>("SalaryCurrency")
                        .HasColumnType("text");

                    b.Property<decimal?>("SalaryExpectations")
                        .HasColumnType("numeric");

                    b.Property<string>("SalaryExpectationsCurrency")
                        .HasColumnType("text");

                    b.Property<string>("Seniority")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UpstreamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UpstreamId")
                        .IsUnique();

                    b.ToTable("SyncedCandidates");
                });

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.SyncedEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("GrossMonthlySalary")
                        .HasColumnType("numeric");

                    b.Property<bool>("HasResume")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBench")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastAccount")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAccountStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MainSkill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ResumeDateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResumeFilename")
                        .HasColumnType("text");

                    b.Property<int?>("ResumeNoteId")
                        .HasColumnType("integer");

                    b.Property<string>("SalaryCurrency")
                        .HasColumnType("text");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UpstreamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UpstreamId")
                        .IsUnique();

                    b.ToTable("SyncedEmployees");
                });

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.SyncedOpenPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountOverview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Aging")
                        .HasColumnType("integer");

                    b.Property<string>("AvailableRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Coe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Countries")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Created")
                        .HasColumnType("text");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastModification")
                        .HasColumnType("text");

                    b.Property<string>("MainSkill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PositionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Practice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReadyDate")
                        .HasColumnType("text");

                    b.Property<bool>("Replacement")
                        .HasColumnType("boolean");

                    b.Property<string>("Seniorities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sourcing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stakeholder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UpstreamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UpstreamId")
                        .IsUnique();

                    b.ToTable("SyncedOpenPositions");
                });

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.TransformSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContextId")
                        .HasColumnType("integer");

                    b.Property<string>("ContextName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("JobDescription")
                        .HasColumnType("text");

                    b.Property<string>("JobDescriptionSource")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessingMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefinementMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResumeContentJson")
                        .HasColumnType("text");

                    b.Property<string>("SelectedPositionId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WizardStateJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("ContextType", "ContextId");

                    b.ToTable("TransformSessions");
                });

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.ResumeSession", b =>
                {
                    b.HasOne("OperationNexus.Api.Models.Entities.ResumeEmbedding", "ResumeEmbedding")
                        .WithMany()
                        .HasForeignKey("ResumeEmbeddingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResumeEmbedding");
                });
#pragma warning restore 612, 618
        }
    }
}
