// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OperationNexus.Api.Data;
using Pgvector;

#nullable disable

namespace OperationNexus.Api.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260314025232_AddCandidateYearSyncFields")]
    partial class AddCandidateYearSyncFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.MatchSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ConstraintsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JdSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchFlowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PipelineStagesJson")
                        .HasColumnType("text");

                    b.Property<string>("PipelineStatsJson")
                        .HasColumnType("text");

                    b.Property<string>("ResultsJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopN")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.ToTable("MatchSessions");
                });

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.ResumeEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)");

                    b.Property<bool>("IsBench")
                        .HasColumnType("boolean");

                    b.Property<string>("ResumeText")
                        .HasColumnType("text");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UpstreamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("ResumeEmbeddings");
                });

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.SyncedCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CoeCertified")
                        .HasColumnType("boolean");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<decimal?>("CurrentSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasResume")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastStatusUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MainSkill")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResumeDateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResumeFilename")
                        .HasColumnType("text");

                    b.Property<int?>("ResumeNoteId")
                        .HasColumnType("integer");

                    b.Property<string>("SalaryCurrency")
                        .HasColumnType("text");

                    b.Property<decimal?>("SalaryExpectations")
                        .HasColumnType("numeric");

                    b.Property<string>("SalaryExpectationsCurrency")
                        .HasColumnType("text");

                    b.Property<string>("Seniority")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UpstreamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UpstreamId")
                        .IsUnique();

                    b.ToTable("SyncedCandidates");
                });

            modelBuilder.Entity("OperationNexus.Api.Models.Entities.SyncedEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("GrossMonthlySalary")
                        .HasColumnType("numeric");

                    b.Property<bool>("HasResume")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBench")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastAccount")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAccountStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MainSkill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ResumeDateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResumeFilename")
                        .HasColumnType("text");

                    b.Property<int?>("ResumeNoteId")
                        .HasColumnType("integer");

                    b.Property<string>("SalaryCurrency")
                        .HasColumnType("text");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UpstreamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UpstreamId")
                        .IsUnique();

                    b.ToTable("SyncedEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
