export const IPC_CHANNELS = {
  SYNC_VALIDATE_TOKEN: 'sync:validate-token',
  SYNC_GET_STATUS: 'sync:get-status',
  SYNC_APPLY_YEAR_FILTER: 'sync:apply-year-filter',
  SYNC_START: 'sync:start',
  SYNC_PAUSE: 'sync:pause',
  SYNC_SINGLE: 'sync:single',
  SYNC_RETRY_FAILED: 'sync:retry-failed',
  SYNC_RETRY_NOT_PROCESSED: 'sync:retry-not-processed',
  SYNC_GET_RECORDS: 'sync:get-records',
  SYNC_CLEAR: 'sync:clear',
  SYNC_GET_SKILLS: 'sync:get-skills',
  SYNC_UPLOAD_NOTE: 'sync:upload-note',

  PROCESSING_VOYAGE_KEY_STATUS: 'processing:voyage-key-status',
  PROCESSING_GET_STATUS: 'processing:get-status',
  PROCESSING_VECTORIZE_SINGLE: 'processing:vectorize-single',
  PROCESSING_START_EXTRACTION: 'processing:start-extraction',
  PROCESSING_PAUSE_EXTRACTION: 'processing:pause-extraction',
  PROCESSING_START_VECTORIZATION: 'processing:start-vectorization',
  PROCESSING_PAUSE_VECTORIZATION: 'processing:pause-vectorization',
  PROCESSING_RETRY_FAILED: 'processing:retry-failed',
  PROCESSING_RETRY_FAILED_VECTORIZATION: 'processing:retry-failed-vectorization',
  PROCESSING_RESET_STATUS: 'processing:reset-status',
  PROCESSING_ADD_VOYAGE_KEY: 'processing:add-voyage-key',
  PROCESSING_REMOVE_VOYAGE_KEY: 'processing:remove-voyage-key',

  MATCH_POOL_COUNTS: 'match:pool-counts',
  MATCH_FILTER_OPTIONS: 'match:filter-options',
  MATCH_SEARCH: 'match:search',
  MATCH_CANCEL_SEARCH: 'match:cancel-search',
  MATCH_CONFIRM_HAIKU: 'match:confirm-haiku',
  MATCH_SEARCH_SESSION: 'match:search-session',
  MATCH_LIST_SESSIONS: 'match:list-sessions',
  MATCH_GET_SESSION: 'match:get-session',
  MATCH_PROXY_STATUS: 'match:proxy-status',
  MATCH_BENCH_EMPLOYEES: 'match:bench-employees',
  MATCH_ALL_EMPLOYEES: 'match:all-employees',
  MATCH_ALL_CANDIDATES: 'match:all-candidates',
  MATCH_SEARCH_CANDIDATES: 'match:search-candidates',
  MATCH_SEARCH_EMPLOYEES: 'match:search-employees',
  MATCH_OPEN_POSITIONS: 'match:open-positions',
  MATCH_BENCH_BURN_SESSION: 'match:bench-burn-session',
  MATCH_BENCH_BURN: 'match:bench-burn',
  MATCH_BENCH_BURN_RETRY: 'match:bench-burn-retry',
  MATCH_RESUME_TEXT: 'match:resume-text',
  MATCH_EXTERNAL_CANDIDATE: 'match:external-candidate',

  SESSIONS_CREATE: 'sessions:create',
  SESSIONS_UPDATE: 'sessions:update',
  SESSIONS_GET: 'sessions:get',
  SESSIONS_LIST: 'sessions:list',
  SESSIONS_DELETE: 'sessions:delete',

  DATABASE_GET_CONFIG: 'database:get-config',
  DATABASE_SAVE_CONFIG: 'database:save-config',
  DATABASE_EXPORT: 'database:export',
  DATABASE_IMPORT: 'database:import',
  DATABASE_LIST_SNAPSHOTS: 'database:list-snapshots',
  DATABASE_STATUS: 'database:status',
  DATABASE_IMPORT_FILE: 'database:import-file',

  SYNC_PROGRESS_EVENT: 'sync:progress-event',
  PROCESSING_PROGRESS_EVENT: 'processing:progress-event',
  MATCH_SEARCH_EVENT: 'match:search-event',
  MATCH_BENCH_BURN_EVENT: 'match:bench-burn-event',

  AI_CHAT: 'ai:chat',
  AI_CHECK_CONNECTION: 'ai:check-connection',

  APP_GET_VERSION: 'app:get-version',
  APP_GET_PLATFORM: 'app:get-platform',
  APP_OPEN_EXTERNAL: 'app:open-external',
  APP_CHECK_FOR_UPDATES: 'app:check-for-updates',
  APP_DOWNLOAD_UPDATE: 'app:download-update',
  APP_INSTALL_UPDATE: 'app:install-update',
  APP_UPDATE_AVAILABLE: 'app:update-available',
  APP_UPDATE_DOWNLOADED: 'app:update-downloaded',
  APP_READ_BUNDLED_FILE: 'app:read-bundled-file',
} as const

export type IpcChannel = typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS]
