export const IPC_CHANNELS = {
  SYNC_VALIDATE_TOKEN: 'sync:validate-token',
  SYNC_GET_STATUS: 'sync:get-status',
  SYNC_APPLY_YEAR_FILTER: 'sync:apply-year-filter',
  SYNC_START: 'sync:start',
  SYNC_PAUSE: 'sync:pause',
  SYNC_SINGLE: 'sync:single',
  SYNC_RETRY_FAILED: 'sync:retry-failed',
  SYNC_RETRY_NOT_PROCESSED: 'sync:retry-not-processed',
  SYNC_GET_RECORDS: 'sync:get-records',
  SYNC_CLEAR: 'sync:clear',
  SYNC_GET_SKILLS: 'sync:get-skills',
  SYNC_UPLOAD_NOTE: 'sync:upload-note',
  SYNC_BACKFILL_SALARY_NORMALIZATION: 'sync:backfill-salary-normalization',

  PROCESSING_VOYAGE_KEY_STATUS: 'processing:voyage-key-status',
  PROCESSING_GET_STATUS: 'processing:get-status',
  PROCESSING_VECTORIZE_SINGLE: 'processing:vectorize-single',
  PROCESSING_START_EXTRACTION: 'processing:start-extraction',
  PROCESSING_PAUSE_EXTRACTION: 'processing:pause-extraction',
  PROCESSING_START_VECTORIZATION: 'processing:start-vectorization',
  PROCESSING_PAUSE_VECTORIZATION: 'processing:pause-vectorization',
  PROCESSING_RETRY_FAILED: 'processing:retry-failed',
  PROCESSING_RETRY_FAILED_VECTORIZATION: 'processing:retry-failed-vectorization',
  PROCESSING_PROCESS_ALL: 'processing:process-all',
  PROCESSING_RESET_STATUS: 'processing:reset-status',
  PROCESSING_ADD_VOYAGE_KEY: 'processing:add-voyage-key',
  PROCESSING_REMOVE_VOYAGE_KEY: 'processing:remove-voyage-key',

  MATCH_POOL_COUNTS: 'match:pool-counts',
  MATCH_FILTER_OPTIONS: 'match:filter-options',
  MATCH_SEARCH: 'match:search',
  MATCH_CANCEL_SEARCH: 'match:cancel-search',
  MATCH_CONFIRM_HAIKU: 'match:confirm-haiku',
  MATCH_SEARCH_SESSION: 'match:search-session',
  MATCH_LIST_SESSIONS: 'match:list-sessions',
  MATCH_GET_SESSION: 'match:get-session',
  MATCH_PROXY_STATUS: 'match:proxy-status',
  MATCH_BENCH_EMPLOYEES: 'match:bench-employees',
  MATCH_ALL_EMPLOYEES: 'match:all-employees',
  MATCH_ALL_CANDIDATES: 'match:all-candidates',
  MATCH_SEARCH_CANDIDATES: 'match:search-candidates',
  MATCH_SEARCH_EMPLOYEES: 'match:search-employees',
  MATCH_OPEN_POSITIONS: 'match:open-positions',
  MATCH_BENCH_BURN_SESSION: 'match:bench-burn-session',
  MATCH_BENCH_BURN: 'match:bench-burn',
  MATCH_BENCH_BURN_RETRY: 'match:bench-burn-retry',
  MATCH_RESUME_TEXT: 'match:resume-text',
  MATCH_EXTERNAL_CANDIDATE: 'match:external-candidate',
  MATCH_CANDIDATE_COUNT: 'match:candidate-count',
  MATCH_EMPLOYEE_COUNT: 'match:employee-count',
  MATCH_ANALYSIS_CACHE_STATS: 'match:analysis-cache-stats',
  MATCH_CLEAR_ANALYSIS_CACHE: 'match:clear-analysis-cache',
  MATCH_RANK_POSITIONS: 'match:rank-positions',
  MATCH_RANK_POSITIONS_FOR_TEXT: 'match:rank-positions-for-text',
  MATCH_TO_POSITIONS: 'match:match-to-positions',

  SESSIONS_CREATE: 'sessions:create',
  SESSIONS_UPDATE: 'sessions:update',
  SESSIONS_GET: 'sessions:get',
  SESSIONS_LIST: 'sessions:list',
  SESSIONS_DELETE: 'sessions:delete',

  DATABASE_GET_CONFIG: 'database:get-config',
  DATABASE_SAVE_CONFIG: 'database:save-config',
  DATABASE_EXPORT: 'database:export',
  DATABASE_IMPORT: 'database:import',
  DATABASE_LIST_SNAPSHOTS: 'database:list-snapshots',
  DATABASE_STATUS: 'database:status',
  DATABASE_IMPORT_FILE: 'database:import-file',
  DATABASE_HEALTH: 'database:health',
  DATABASE_SYNC_CHECK: 'database:sync-check',
  DATABASE_SYNC_STATUS: 'database:sync-status',
  DATABASE_IMPORT_LATEST: 'database:import-latest',
  DATABASE_SYNC_UPDATE: 'database:sync-update',
  DATABASE_SELECT_DIRECTORY: 'database:select-directory',

  PIPELINE_START: 'pipeline:start',
  PIPELINE_PAUSE: 'pipeline:pause',
  PIPELINE_RETRY_ALL_FAILED: 'pipeline:retry-all-failed',
  PIPELINE_RETRY_SINGLE: 'pipeline:retry-single',
  PIPELINE_GET_FAILED: 'pipeline:get-failed',
  PIPELINE_GET_STATE: 'pipeline:get-state',
  PIPELINE_CLEAR_STATE: 'pipeline:clear-state',

  SYNC_PROGRESS_EVENT: 'sync:progress-event',
  PROCESSING_PROGRESS_EVENT: 'processing:progress-event',
  PIPELINE_PROGRESS_EVENT: 'pipeline:progress-event',
  MATCH_SEARCH_EVENT: 'match:search-event',
  MATCH_BENCH_BURN_EVENT: 'match:bench-burn-event',

  AI_CHAT: 'ai:chat',
  AI_CHECK_CONNECTION: 'ai:check-connection',
  AI_TOKEN_USAGE: 'ai:token-usage',
  AI_RESET_TOKEN_USAGE: 'ai:reset-token-usage',
  AI_SUBSCRIPTION_STATUS: 'ai:subscription-status',

  APP_GET_VERSION: 'app:get-version',
  APP_GET_PLATFORM: 'app:get-platform',
  APP_OPEN_EXTERNAL: 'app:open-external',
  APP_CHECK_FOR_UPDATES: 'app:check-for-updates',
  APP_DOWNLOAD_UPDATE: 'app:download-update',
  APP_INSTALL_UPDATE: 'app:install-update',
  APP_UPDATE_AVAILABLE: 'app:update-available',
  APP_UPDATE_DOWNLOADED: 'app:update-downloaded',
  APP_READ_BUNDLED_FILE: 'app:read-bundled-file',
  APP_SHOW_ITEM_IN_FOLDER: 'app:show-item-in-folder',
  APP_OPEN_PATH: 'app:open-path',
  APP_NAVIGATE: 'app:navigate',

  REPORT_EVALUATE_POSITIONS: 'report:evaluate-positions',
  REPORT_POSITION_DETAIL: 'report:position-detail',
  REPORT_EXPORT_CSV: 'report:export-csv',
  REPORT_GET_SYNC_STATUS: 'report:get-sync-status',
  REPORT_GET_FEEDBACK_CATALOG: 'report:get-feedback-catalog',
  REPORT_GET_FEEDBACK_CATALOG_LOCAL: 'report:get-feedback-catalog-local',
  REPORT_DELETE_POSITION: 'report:delete-position',
  REPORT_EXPORT_PDF: 'report:export-pdf',
  REPORT_EXPORT_XLSX: 'report:export-xlsx',
  REPORT_ACCEPTANCE_RATE: 'report:acceptance-rate',
  REPORT_ACCEPTANCE_RATE_COES: 'report:acceptance-rate-coes',
  REPORT_PLACEMENT_MARGIN: 'report:placement-margin',
  REPORT_FILL_RATE: 'report:fill-rate',

  SYNC_PLACEMENT_MARGIN: 'sync:placement-margin',
  SYNC_PLACEMENT_MARGIN_STATUS: 'sync:placement-margin-status',

  SYNC_OFFBOARDING: 'sync:offboarding',
  SYNC_OFFBOARDING_STATUS: 'sync:offboarding-status',
  REPORT_OFFBOARDING: 'report:offboarding',

  COE_TRACKING_GET_OVERVIEW: 'coe-tracking:get-overview',
  COE_TRACKING_GET_COE_DETAIL: 'coe-tracking:get-coe-detail',
  COE_TRACKING_GET_PRACTICE_DETAIL: 'coe-tracking:get-practice-detail',
  COE_TRACKING_GET_PRACTICE_POSITIONS: 'coe-tracking:get-practice-positions',
  COE_TRACKING_GET_SKILL_POSITIONS: 'coe-tracking:get-skill-positions',
  COE_TRACKING_GET_POSITION_DETAIL: 'coe-tracking:get-position-detail',
  COE_TRACKING_GET_COE_POSITIONS: 'coe-tracking:get-coe-positions',
  COE_TRACKING_GET_SYNC_STATUS: 'coe-tracking:get-sync-status',

  PRR_GET_ALL: 'prr:get-all',
  PRR_GET_DETAIL: 'prr:get-detail',
  PRR_UPDATE_COE_STATUS: 'prr:update-coe-status',
  PRR_ADD_COMMENT: 'prr:add-comment',
  PRR_DELETE: 'prr:delete',
  PRR_GET_SYNC_STATUS: 'prr:get-sync-status',
  PRR_EXPORT_XLSX: 'prr:export-xlsx',

  ERRORS_LIST: 'errors:list',
  ERRORS_CLEAR: 'errors:clear',
  ERRORS_MARK_REPORTED: 'errors:mark-reported',
  ERRORS_GENERATE_DESCRIPTION: 'errors:generate-description',
  ERRORS_REPORT: 'errors:report',
  ERRORS_GET_LOG_PATH: 'errors:get-log-path',
  ERRORS_NEW_EVENT: 'errors:new-event',

  NOMICORE_LOGIN: 'nomicore:login',
  NOMICORE_CHECK_SESSION: 'nomicore:check-session',
  NOMICORE_CALCULATE: 'nomicore:calculate',

  PRESENT_CREATE_SESSION: 'present:create-session',
  PRESENT_UPDATE_SESSION: 'present:update-session',
  PRESENT_GET_SESSION: 'present:get-session',
  PRESENT_LIST_SESSIONS: 'present:list-sessions',
  PRESENT_DELETE_SESSION: 'present:delete-session',
  PRESENT_ADD_ENTRY: 'present:add-entry',
  PRESENT_UPDATE_ENTRY: 'present:update-entry',
  PRESENT_DELETE_ENTRY: 'present:delete-entry',
  PRESENT_CHECK_RESUME_FORMAT: 'present:check-resume-format',
  PRESENT_TRANSFORM_RESUME: 'present:transform-resume',
  PRESENT_GENERATE_INTRO: 'present:generate-intro',
  PRESENT_GENERATE_CANDIDATE_PROFILE: 'present:generate-candidate-profile',
  PRESENT_GENERATE_HTML: 'present:generate-html',

  POSITION_PIPELINE_START: 'position-pipeline:start',
  POSITION_PIPELINE_PAUSE: 'position-pipeline:pause',
  POSITION_PIPELINE_VECTORIZE_SYNCED: 'position-pipeline:vectorize-synced',
  POSITION_PIPELINE_RETRY_ALL_FAILED: 'position-pipeline:retry-all-failed',
  POSITION_PIPELINE_RETRY_SINGLE: 'position-pipeline:retry-single',
  POSITION_PIPELINE_GET_FAILED: 'position-pipeline:get-failed',
  POSITION_PIPELINE_GET_STATE: 'position-pipeline:get-state',
  POSITION_PIPELINE_CLEAR_STATE: 'position-pipeline:clear-state',
  POSITION_PIPELINE_PROGRESS_EVENT: 'position-pipeline:progress-event',

  MAIL_GET_CONFIG: 'mail:get-config',
  MAIL_SAVE_CONFIG: 'mail:save-config',
  MAIL_CLEAR_CONFIG: 'mail:clear-config',
  MAIL_TEST_CONNECTION: 'mail:test-connection',

  RESPONSIVENESS_GET_REPORT: 'responsiveness:get-report',
  RESPONSIVENESS_GET_LEADS: 'responsiveness:get-leads',
  RESPONSIVENESS_ADD_LEAD: 'responsiveness:add-lead',
  RESPONSIVENESS_REMOVE_LEAD: 'responsiveness:remove-lead',
  RESPONSIVENESS_GET_POSITION_DISCUSSIONS: 'responsiveness:get-position-discussions',
  RESPONSIVENESS_ANALYZE_MENTIONS: 'responsiveness:analyze-mentions',

  RESPONSIVENESS_GENERATE_FULL_REPORT: 'responsiveness:generate-full-report',
  RESPONSIVENESS_GENERATE_PROGRESS: 'responsiveness:generate-progress',
  RESPONSIVENESS_GET_LAST_REPORT: 'responsiveness:get-last-report',

  // Model Configuration
  MODEL_CONFIG_GET: 'model-config:get',
  MODEL_CONFIG_SAVE: 'model-config:save',
  MODEL_CONFIG_LOCAL_HEALTH: 'model-config:local-health',
  MODEL_CONFIG_LOCAL_MODELS: 'model-config:local-models',

  // Catalog Management
  CATALOG_GET_COES: 'catalog:get-coes',
  CATALOG_GET_COE: 'catalog:get-coe',
  CATALOG_CREATE_COE: 'catalog:create-coe',
  CATALOG_UPDATE_COE: 'catalog:update-coe',
  CATALOG_TOGGLE_COE: 'catalog:toggle-coe',
  CATALOG_ADD_PRACTICE_TO_COE: 'catalog:add-practice-to-coe',
  CATALOG_REMOVE_PRACTICE_FROM_COE: 'catalog:remove-practice-from-coe',

  CATALOG_GET_PRACTICES: 'catalog:get-practices',
  CATALOG_GET_PRACTICE: 'catalog:get-practice',
  CATALOG_CREATE_PRACTICE: 'catalog:create-practice',
  CATALOG_UPDATE_PRACTICE: 'catalog:update-practice',
  CATALOG_TOGGLE_PRACTICE: 'catalog:toggle-practice',
  CATALOG_ADD_SKILL_TO_PRACTICE: 'catalog:add-skill-to-practice',
  CATALOG_REMOVE_SKILL_FROM_PRACTICE: 'catalog:remove-skill-from-practice',

  CATALOG_GET_SKILLS: 'catalog:get-skills',
  CATALOG_GET_SKILL: 'catalog:get-skill',
  CATALOG_CREATE_SKILL: 'catalog:create-skill',
  CATALOG_UPDATE_SKILL: 'catalog:update-skill',
  CATALOG_TOGGLE_SKILL: 'catalog:toggle-skill',

  // Practice Lead Bonus
  PRACTICE_LEAD_BONUS_PLACEMENTS: 'practice-lead-bonus:placements',
  PRACTICE_LEAD_BONUS_OFFBOARDINGS: 'practice-lead-bonus:offboardings',
  PRACTICE_LEAD_BONUS_OVERVIEW: 'practice-lead-bonus:overview',
  PRACTICE_LEAD_BONUS_GET_PRACTICE_LEADS: 'practice-lead-bonus:get-practice-leads',
  PRACTICE_LEAD_BONUS_SAVE_GM_OVERRIDE: 'practice-lead-bonus:save-gm-override',
} as const

export type IpcChannel = typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS]
