import type {
  BraniacRunParams,
  BraniacCancelParams,
  BraniacChatParams,
  BraniacClearPatternsParams,
  BraniacClearAccountParams,
  BraniacClearStakeholderParams,
  BraniacCreatePatternParams,
  BraniacBeautifyPatternParams,
  BraniacDeletePatternParams,
  BraniacDeleteProfileParams,
  BraniacExtractResumeSkillsParams,
  BraniacGetAccountSummaryParams,
  BraniacGetAnalysisStatusParams,
  BraniacGetStakeholdersParams,
  BraniacListJobsParams,
  BraniacListPatternsParams,
  BraniacListProfilesParams,
  BraniacGetProfileParams,
  BraniacApprovePatternParams,
  BraniacRejectPatternParams,
  BraniacUpdatePatternParams,
  AgentStepEvent,
  BraniacStatusEvent,
} from '../../../../shared/ipc-types'

export const braniacService = {
  run: (params: BraniacRunParams) => window.api.braniac.run(params),
  cancel: (params: BraniacCancelParams) => window.api.braniac.cancel(params),
  getStatus: () => window.api.braniac.getStatus(),
  listJobs: (params?: BraniacListJobsParams) => window.api.braniac.listJobs(params),
  getJob: (jobId: string) => window.api.braniac.getJob(jobId),
  listPatterns: (params?: BraniacListPatternsParams) => window.api.braniac.listPatterns(params),
  listProfiles: (params?: BraniacListProfilesParams) => window.api.braniac.listProfiles(params),
  getProfile: (params: BraniacGetProfileParams) => window.api.braniac.getProfile(params),
  getAccounts: () => window.api.braniac.getAccounts(),
  approvePattern: (params: BraniacApprovePatternParams) => window.api.braniac.approvePattern(params),
  rejectPattern: (params: BraniacRejectPatternParams) => window.api.braniac.rejectPattern(params),
  updatePattern: (params: BraniacUpdatePatternParams) => window.api.braniac.updatePattern(params),
  getStakeholders: (params: BraniacGetStakeholdersParams) => window.api.braniac.getStakeholders(params),
  getAnalysisStatus: (params: BraniacGetAnalysisStatusParams) => window.api.braniac.getAnalysisStatus(params),
  createPattern: (params: BraniacCreatePatternParams) => window.api.braniac.createPattern(params),
  beautifyPattern: (params: BraniacBeautifyPatternParams) => window.api.braniac.beautifyPattern(params),
  clearPatterns: (params: BraniacClearPatternsParams) => window.api.braniac.clearPatterns(params),
  listAccountSummaries: () => window.api.braniac.listAccountSummaries(),
  getAccountSummary: (params: BraniacGetAccountSummaryParams) => window.api.braniac.getAccountSummary(params),
  deletePattern: (params: BraniacDeletePatternParams) => window.api.braniac.deletePattern(params),
  deleteProfile: (params: BraniacDeleteProfileParams) => window.api.braniac.deleteProfile(params),
  clearStakeholder: (params: BraniacClearStakeholderParams) => window.api.braniac.clearStakeholder(params),
  clearAccount: (params: BraniacClearAccountParams) => window.api.braniac.clearAccount(params),
  chat: (params: BraniacChatParams) => window.api.braniac.chat(params),
  extractResumeSkills: (params: BraniacExtractResumeSkillsParams) => window.api.braniac.extractResumeSkills(params),
  getExtractionStatus: () => window.api.braniac.getExtractionStatus(),
  onStepEvent: (cb: (data: AgentStepEvent) => void) => window.api.braniac.onStepEvent(cb),
  onStatusEvent: (cb: (data: BraniacStatusEvent) => void) => window.api.braniac.onStatusEvent(cb),
  onChatStepEvent: (callback: (step: string) => void) =>
    window.api.braniac.onChatStepEvent(callback),
  onChatChunkEvent: (callback: (text: string) => void) =>
    window.api.braniac.onChatChunkEvent((data) => callback(data.text)),
}
