import type {
  Scout9RunParams,
  Scout9ListReportsParams,
  Scout9UpdateCandidateParams,
  Scout9SubmitSkipParams,
  Scout9CreateRuleParams,
  Scout9UpdateRuleParams,
  Scout9CreateGlossaryTermParams,
  Scout9UpdateGlossaryTermParams,
  Scout9CreateNoteParams,
  Scout9UpdateNoteParams,
  Scout9TogglePatternParams,
  Scout9CreateOverrideParams,
  Scout9UpdateConfigParams,
  Scout9CreatePromptVersionParams,
  Scout9ActivatePromptVersionParams,
  Scout9PipelineEvent,
  Scout9StatusEvent,
} from '../../../../shared/ipc-types'

export const scout9Service = {
  run: (params: Scout9RunParams) => window.api.scout9.run(params),
  cancel: () => window.api.scout9.cancel(),
  getStatus: () => window.api.scout9.getStatus(),
  getScopeOptions: () => window.api.scout9.getScopeOptions(),
  listReports: (params?: Scout9ListReportsParams) => window.api.scout9.listReports(params),
  getReport: (reportId: string) => window.api.scout9.getReport(reportId),
  updateCandidate: (params: Scout9UpdateCandidateParams) => window.api.scout9.updateCandidate(params),
  submitSkip: (params: Scout9SubmitSkipParams) => window.api.scout9.submitSkip(params),
  listRules: () => window.api.scout9.listRules(),
  createRule: (params: Scout9CreateRuleParams) => window.api.scout9.createRule(params),
  updateRule: (params: Scout9UpdateRuleParams) => window.api.scout9.updateRule(params),
  deleteRule: (id: string) => window.api.scout9.deleteRule(id),
  listGlossary: () => window.api.scout9.listGlossary(),
  createGlossaryTerm: (params: Scout9CreateGlossaryTermParams) => window.api.scout9.createGlossaryTerm(params),
  updateGlossaryTerm: (params: Scout9UpdateGlossaryTermParams) => window.api.scout9.updateGlossaryTerm(params),
  deleteGlossaryTerm: (id: string) => window.api.scout9.deleteGlossaryTerm(id),
  listNotes: () => window.api.scout9.listNotes(),
  createNote: (params: Scout9CreateNoteParams) => window.api.scout9.createNote(params),
  updateNote: (params: Scout9UpdateNoteParams) => window.api.scout9.updateNote(params),
  deleteNote: (id: string) => window.api.scout9.deleteNote(id),
  compileKnowledgeBase: () => window.api.scout9.compileKnowledgeBase(),
  listPatterns: () => window.api.scout9.listPatterns(),
  togglePattern: (params: Scout9TogglePatternParams) => window.api.scout9.togglePattern(params),
  listOverrides: (clientId?: string) => window.api.scout9.listOverrides(clientId),
  createOverride: (params: Scout9CreateOverrideParams) => window.api.scout9.createOverride(params),
  deleteOverride: (id: string) => window.api.scout9.deleteOverride(id),
  getTokenBudget: () => window.api.scout9.getTokenBudget(),
  getConfig: () => window.api.scout9.getConfig(),
  updateConfig: (params: Scout9UpdateConfigParams) => window.api.scout9.updateConfig(params),
  listPromptVersions: () => window.api.scout9.listPromptVersions(),
  createPromptVersion: (params: Scout9CreatePromptVersionParams) => window.api.scout9.createPromptVersion(params),
  activatePromptVersion: (params: Scout9ActivatePromptVersionParams) => window.api.scout9.activatePromptVersion(params),
  getBrainSnapshot: () => window.api.scout9.getBrainSnapshot(),
  onPipelineEvent: (callback: (event: Scout9PipelineEvent) => void) =>
    window.api.scout9.onPipelineEvent(callback),
  onStatusEvent: (callback: (event: Scout9StatusEvent) => void) =>
    window.api.scout9.onStatusEvent(callback),
}
