import '@testing-library/jest-dom/vitest';
import { vi } from 'vitest';

if (typeof globalThis.DOMMatrix === 'undefined') {
  globalThis.DOMMatrix = class DOMMatrix {
    constructor() { return Object.create(DOMMatrix.prototype); }
    static fromMatrix() { return new DOMMatrix(); }
    static fromFloat32Array() { return new DOMMatrix(); }
    static fromFloat64Array() { return new DOMMatrix(); }
  } as unknown as typeof globalThis.DOMMatrix;
}

Object.defineProperty(window, 'api', {
  value: {
    sync: {
      validateToken: vi.fn().mockResolvedValue({ valid: false }),
      getStatus: vi.fn().mockResolvedValue({}),
      applyYearFilter: vi.fn().mockResolvedValue({}),
      start: vi.fn().mockResolvedValue({}),
      pause: vi.fn().mockResolvedValue({}),
      syncSingle: vi.fn().mockResolvedValue({}),
      retryFailed: vi.fn().mockResolvedValue({}),
      retryNotProcessed: vi.fn().mockResolvedValue({}),
      getRecords: vi.fn().mockResolvedValue([]),
      clear: vi.fn().mockResolvedValue({}),
      getSkills: vi.fn().mockResolvedValue([]),
      uploadNote: vi.fn().mockResolvedValue({}),
      onProgress: vi.fn().mockReturnValue(() => {}),
    },
    processing: {
      getVoyageKeyStatus: vi.fn().mockResolvedValue({ configured: false }),
      getStatus: vi.fn().mockResolvedValue({}),
      vectorizeSingle: vi.fn().mockResolvedValue({}),
      startExtraction: vi.fn().mockResolvedValue({}),
      pauseExtraction: vi.fn().mockResolvedValue({}),
      startVectorization: vi.fn().mockResolvedValue({}),
      pauseVectorization: vi.fn().mockResolvedValue({}),
      retryFailed: vi.fn().mockResolvedValue({}),
      retryFailedVectorization: vi.fn().mockResolvedValue({}),
      processAll: vi.fn().mockResolvedValue({}),
      resetStatus: vi.fn().mockResolvedValue({}),
      addVoyageKey: vi.fn().mockResolvedValue({ saved: true }),
      removeVoyageKey: vi.fn().mockResolvedValue({ deleted: true }),
      onProgress: vi.fn().mockReturnValue(() => {}),
    },
    match: {
      getPoolCounts: vi.fn().mockResolvedValue({ candidates: 0, employees: 0, positions: 0 }),
      getFilterOptions: vi.fn().mockResolvedValue({ skills: [], seniorities: [], accounts: [] }),
      search: vi.fn().mockResolvedValue({}),
      cancelSearch: vi.fn().mockResolvedValue({}),
      confirmHaiku: vi.fn().mockResolvedValue({}),
      searchSession: vi.fn().mockResolvedValue({}),
      listSessions: vi.fn().mockResolvedValue([]),
      getSession: vi.fn().mockResolvedValue({}),
      getProxyStatus: vi.fn().mockResolvedValue({ available: false }),
      getBenchEmployees: vi.fn().mockResolvedValue([]),
      getAllEmployees: vi.fn().mockResolvedValue([]),
      getAllCandidates: vi.fn().mockResolvedValue([]),
      searchCandidates: vi.fn().mockResolvedValue([]),
      searchEmployees: vi.fn().mockResolvedValue([]),
      getOpenPositions: vi.fn().mockResolvedValue([]),
      getBenchBurnSession: vi.fn().mockResolvedValue({}),
      benchBurn: vi.fn().mockResolvedValue({}),
      benchBurnRetry: vi.fn().mockResolvedValue({}),
      getResumeText: vi.fn().mockResolvedValue(''),
      externalCandidate: vi.fn().mockResolvedValue({}),
      onSearchEvent: vi.fn().mockReturnValue(() => {}),
      onBenchBurnEvent: vi.fn().mockReturnValue(() => {}),
    },
    sessions: {
      create: vi.fn().mockResolvedValue({ id: 1 }),
      update: vi.fn().mockResolvedValue({}),
      get: vi.fn().mockResolvedValue({}),
      list: vi.fn().mockResolvedValue([]),
      delete: vi.fn().mockResolvedValue({}),
    },
    database: {
      getConfig: vi.fn().mockResolvedValue({ isConfigured: false, sharedPath: '', exporterName: '' }),
      saveConfig: vi.fn().mockResolvedValue({}),
      export: vi.fn().mockResolvedValue({}),
      import: vi.fn().mockResolvedValue({ success: true }),
      listSnapshots: vi.fn().mockResolvedValue({ snapshots: [] }),
      getStatus: vi.fn().mockResolvedValue({}),
      importFile: vi.fn().mockResolvedValue({ success: true }),
      getHealth: vi.fn().mockResolvedValue({ healthy: true }),
    },
    ai: {
      chat: vi.fn().mockResolvedValue({ content: '' }),
      checkConnection: vi.fn().mockResolvedValue({ connected: false }),
    },
    report: {
      evaluatePositions: vi.fn().mockResolvedValue({ results: [] }),
      getPositionDetail: vi.fn().mockResolvedValue(null),
      exportCsv: vi.fn().mockResolvedValue({ success: true }),
      getSyncStatus: vi.fn().mockResolvedValue({ lastSyncAt: null }),
      getFeedbackCatalog: vi.fn().mockResolvedValue([]),
      deletePosition: vi.fn().mockResolvedValue({ success: true }),
      exportPdf: vi.fn().mockResolvedValue({ success: true }),
    },
    prr: {
      getAll: vi.fn().mockResolvedValue([]),
      getDetail: vi.fn().mockResolvedValue(null),
      updateCoeStatus: vi.fn().mockResolvedValue({ success: true }),
      addComment: vi.fn().mockResolvedValue({ success: true }),
      delete: vi.fn().mockResolvedValue({ success: true }),
      getSyncStatus: vi.fn().mockResolvedValue({ lastSyncAt: null }),
    },
    path: {
      getDeveloperDashboard: vi.fn().mockResolvedValue(null),
      listLearningPaths: vi.fn().mockResolvedValue([]),
      getLearningPath: vi.fn().mockResolvedValue(null),
      createLearningPath: vi.fn().mockResolvedValue({ id: 1 }),
      updateLearningPath: vi.fn().mockResolvedValue({ success: true }),
      deleteLearningPath: vi.fn().mockResolvedValue({ success: true }),
      listAssessments: vi.fn().mockResolvedValue([]),
      getAssessment: vi.fn().mockResolvedValue(null),
      saveAssessmentDraft: vi.fn().mockResolvedValue({ success: true }),
      submitAssessment: vi.fn().mockResolvedValue({ success: true }),
      listDiscussionThreads: vi.fn().mockResolvedValue([]),
      getDiscussionThread: vi.fn().mockResolvedValue(null),
      createDiscussionPost: vi.fn().mockResolvedValue({ id: 1 }),
      replyDiscussionPost: vi.fn().mockResolvedValue({ id: 1 }),
      listDossiers: vi.fn().mockResolvedValue([]),
      getDossier: vi.fn().mockResolvedValue(null),
      updateDossierStatus: vi.fn().mockResolvedValue({ success: true }),
      getAdminAnalytics: vi.fn().mockResolvedValue({}),
      getSettings: vi.fn().mockResolvedValue({}),
      saveSettings: vi.fn().mockResolvedValue({ success: true }),
      saveAnalyticsEvent: vi.fn().mockResolvedValue({ success: true }),
      recalculateReadiness: vi.fn().mockResolvedValue({}),
      generateDefensePrep: vi.fn().mockResolvedValue({}),
      generateRemediation: vi.fn().mockResolvedValue({}),
      searchDynamicResources: vi.fn().mockResolvedValue([]),
    },
    scout9: {
      run: vi.fn().mockResolvedValue({ jobId: 'test' }),
      cancel: vi.fn().mockResolvedValue({ success: true }),
      getStatus: vi.fn().mockResolvedValue({ running: false }),
      getScopeOptions: vi.fn().mockResolvedValue({ presets: [] }),
      listReports: vi.fn().mockResolvedValue([]),
      getReport: vi.fn().mockResolvedValue(null),
      updateCandidate: vi.fn().mockResolvedValue({ success: true }),
      submitSkip: vi.fn().mockResolvedValue({ success: true }),
      listRules: vi.fn().mockResolvedValue([]),
      createRule: vi.fn().mockResolvedValue({ id: 'rule-1' }),
      updateRule: vi.fn().mockResolvedValue({ success: true }),
      deleteRule: vi.fn().mockResolvedValue({ success: true }),
      listGlossary: vi.fn().mockResolvedValue([]),
      createGlossaryTerm: vi.fn().mockResolvedValue({ id: 'term-1' }),
      updateGlossaryTerm: vi.fn().mockResolvedValue({ success: true }),
      deleteGlossaryTerm: vi.fn().mockResolvedValue({ success: true }),
      listNotes: vi.fn().mockResolvedValue([]),
      createNote: vi.fn().mockResolvedValue({ id: 'note-1' }),
      updateNote: vi.fn().mockResolvedValue({ success: true }),
      deleteNote: vi.fn().mockResolvedValue({ success: true }),
      compileKnowledgeBase: vi.fn().mockResolvedValue({ success: true }),
      listPatterns: vi.fn().mockResolvedValue([]),
      togglePattern: vi.fn().mockResolvedValue({ success: true }),
      listOverrides: vi.fn().mockResolvedValue([]),
      createOverride: vi.fn().mockResolvedValue({ id: 'override-1' }),
      deleteOverride: vi.fn().mockResolvedValue({ success: true }),
      getTokenBudget: vi.fn().mockResolvedValue({ total: 0, used: 0 }),
      getConfig: vi.fn().mockResolvedValue({}),
      updateConfig: vi.fn().mockResolvedValue({ success: true }),
      listPromptVersions: vi.fn().mockResolvedValue([]),
      createPromptVersion: vi.fn().mockResolvedValue({ id: 'prompt-1' }),
      activatePromptVersion: vi.fn().mockResolvedValue({ success: true }),
      getBrainSnapshot: vi.fn().mockResolvedValue(null),
      onPipelineEvent: vi.fn().mockReturnValue(() => {}),
      onStatusEvent: vi.fn().mockReturnValue(() => {}),
    },
    vigil: {
      run: vi.fn().mockResolvedValue({ runId: 'test' }),
      cancelRun: vi.fn().mockResolvedValue({ success: true }),
      getStatus: vi.fn().mockResolvedValue({ running: false }),
      listRuns: vi.fn().mockResolvedValue([]),
      getRun: vi.fn().mockResolvedValue(null),
      getActivityLog: vi.fn().mockResolvedValue([]),
      clearActivityLog: vi.fn().mockResolvedValue({ success: true }),
      getConfig: vi.fn().mockResolvedValue({}),
      updateConfig: vi.fn().mockResolvedValue({ success: true }),
      sendMessage: vi.fn().mockResolvedValue({ message: '' }),
      listMessages: vi.fn().mockResolvedValue([]),
      clearMessages: vi.fn().mockResolvedValue({ success: true }),
      toolsDryRun: vi.fn().mockResolvedValue({}),
      syncSource: vi.fn().mockResolvedValue({ success: true }),
      onActivityEvent: vi.fn().mockReturnValue(() => {}),
      onStatusEvent: vi.fn().mockReturnValue(() => {}),
    },
    agents: {
      runStub: vi.fn().mockResolvedValue({ success: true }),
      onStepEvent: vi.fn().mockReturnValue(() => {}),
    },
    braniac: {
      run: vi.fn().mockResolvedValue({ jobId: 'test' }),
      cancel: vi.fn().mockResolvedValue({ success: true }),
      getStatus: vi.fn().mockResolvedValue({ running: false }),
      listJobs: vi.fn().mockResolvedValue([]),
      getJob: vi.fn().mockResolvedValue(null),
      listPatterns: vi.fn().mockResolvedValue([]),
      listProfiles: vi.fn().mockResolvedValue([]),
      getProfile: vi.fn().mockResolvedValue(null),
      getAccounts: vi.fn().mockResolvedValue([]),
      onStepEvent: vi.fn().mockReturnValue(() => {}),
      onStatusEvent: vi.fn().mockReturnValue(() => {}),
    },
    app: {
      getVersion: vi.fn().mockResolvedValue('1.0.0'),
      getPlatform: vi.fn().mockResolvedValue('darwin'),
      openExternal: vi.fn().mockResolvedValue(undefined),
      checkForUpdates: vi.fn().mockResolvedValue(null),
      downloadUpdate: vi.fn().mockResolvedValue({ success: true }),
      installUpdate: vi.fn().mockResolvedValue(undefined),
      onUpdateAvailable: vi.fn().mockReturnValue(() => {}),
      onUpdateDownloaded: vi.fn().mockReturnValue(() => {}),
      readBundledFile: vi.fn().mockResolvedValue(''),
      showItemInFolder: vi.fn().mockResolvedValue(undefined),
      openPath: vi.fn().mockResolvedValue(undefined),
    },
  },
  writable: true,
  configurable: true,
});
